# Generated by Django 5.1.1 on 2024-09-09 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the product.",
                        max_length=255,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Enter a brief description of the product.",
                        max_length=500,
                        verbose_name="Product Description",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Enter the value of the product.",
                        max_digits=10,
                        verbose_name="Product Value",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "indexes": [
                    models.Index(fields=["user"], name="products_pr_user_id_53911a_idx")
                ],
            },
        ),
    ]
